language: node_js
node_js:
- '10'
before_install:
- printf "registry=https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
install:
- yarn install
script:
  - yarn lint
  - yarn test
branches:
  only:
  - master
  - /^v?\d+(\.\d+)+[\.\-_\w]*/
deploy:
  provider: npm
  email: nanyuantingfeng@aliyun.com
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: true
    repo: nanyuantingfeng/markdown-rc-loader
